version: '3.8'

services:
  snort3:
    image: ciscotalos/snort3
    container_name: snort3
    hostname: snort3
    user: root
    network_mode: host
    cap_add:
      - NET_ADMIN
      - NET_RAW
      - SYS_RAWIO
    working_dir: /home/snorty
    volumes:
      - ./new.rules:/home/snorty/snort3/etc/rules/new.rules:ro
      - ./snort.lua:/home/snorty/snort3/etc/snort/snort.lua:ro
      - ./.bashrc:/root/.bashrc:ro
    command: ["/bin/bash"]
    stdin_open: true
    tty: true
    restart: on-failure:5
